name: Build React + .NET Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    # Setup Node
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    # Install React dependencies
    - name: Install Frontend Dependencies
      run: |
        cd StudentUi
        npm install

    # Build React app
    - name: Build React
      run: |
        cd StudentUi
        npm run build

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # Restore backend
    - name: Restore Backend
      run: |
        cd StudentApi
        dotnet restore

    # Build backend
    - name: Build Backend
      run: |
        cd StudentApi
        dotnet build --configuration Release
